export const TABLE_HEADER_STANDARD = 'Contrôle'
export const TABLE_HEADER_STATUS = 'Statut'
export const TABLE_HEADER_PERCENTAGE = 'Pourcentage'

export const standards = [
    {
        standard: '4',
        description: 'Contexte de l\'organisation',
        subSections: [
            { standard: '4.1', description: 'Compréhension de l\'organisation et de son contexte' },
            { standard: '4.2', description: 'Compréhension des besoins et attentes des parties intéressées' },
            { standard: '4.3', description: 'Détermination du domaine d\'application du système de management de la sécurité de l\'information' },
            { standard: '4.4', description: 'Système de management de la sécurité de l\'information' }
        ]
    },
    {
        standard: '5',
        description: 'Leadership',
        subSections: [
            { standard: '5.1', description: 'Leadership et engagement' },
            { standard: '5.2', description: 'Politique' },
            { standard: '5.3', description: 'Rôles, responsabilités et autorités au sein de l\'organisation' }
        ]
    },
    {
        standard: '6',
        description: 'Planification',
        subSections: [
            { standard: '6.1.1', description: 'Généralités' },
            { standard: '6.1.2', description: 'Appréciation des risques de sécurité de l\'information' },
            { standard: '6.1.3', description: 'Traitement des risques de sécurité de l\'information' },
            { standard: '6.2', description: 'Objectifs de sécurité de l\'information et plans pour les atteindre' },
            { standard: '6.3', description: 'Planification des modifications' }
        ]
    },
    {
        standard: '7',
        description: 'Supports',
        subSections: [
            { standard: '7.1', description: 'Ressources' },
            { standard: '7.2', description: 'Compétences' },
            { standard: '7.3', description: 'Sensibilisation' },
            { standard: '7.4', description: 'Communication' },
            { standard: '7.5.1', description: 'Généralités' },
            { standard: '7.5.2', description: 'Création et mise à jour' },
            { standard: '7.5.3', description: 'Contrôle des informations documentées' }
        ]
    },
    {
        standard: '8',
        description: 'Fonctionnement',
        subSections: [
            { standard: '8.1', description: 'Planification et contrôle opérationnels' },
            { standard: '8.2', description: 'Appréciation des risques de sécurité de l\'information' },
            { standard: '8.3', description: 'Traitement des risques de sécurité de l\'information' }
        ]
    },
    {
        standard: '9',
        description: 'Évaluation de la performance',
        subSections: [
            { standard: '9.1', description: 'Surveillance, mesurages, analyse et évaluation' },
            { standard: '9.2.1', description: 'Généralités' },
            { standard: '9.2.2', description: 'Programme d\'audit interne' },
            { standard: '9.3.1', description: 'Généralités' },
            { standard: '9.3.2', description: 'Éléments d\'entrée de la revue de direction' },
            { standard: '9.3.3', description: 'Résultats des revues de direction' }
        ]
    },
    {
        standard: '10',
        description: 'Amélioration',
        subSections: [
            { standard: '10.1', description: 'Amélioration continue' },
            { standard: '10.2', description: 'Non-conformité et action corrective' }
        ]
    }
]

export const controls = [
    { standard: '4.1.1', checklistValue: 0, findings: '', status: 0, description: 'Déterminer les enjeux internes et externes affectant le SMSI.' },
    { standard: '4.2.1', checklistValue: 0, findings: '', status: 0, description: 'Identifier les parties intéressées concernées.' },
    { standard: '4.2.2', checklistValue: 0, findings: '', status: 0, description: 'Identifier leurs exigences pertinentes.' },
    { standard: '4.2.3', checklistValue: 0, findings: '', status: 0, description: 'Déterminer quelles exigences seront traitées par le SMSI.' },
    { standard: '4.3.1', checklistValue: 0, findings: '', status: 0, description: 'Définir les limites et l’applicabilité du SMSI.' },
    { standard: '4.3.2', checklistValue: 0, findings: '', status: 0, description: 'Considérer les enjeux internes/externes (4.1).' },
    { standard: '4.3.3', checklistValue: 0, findings: '', status: 0, description: 'Considérer les exigences des parties intéressées (4.2).' },
    { standard: '4.3.4', checklistValue: 0, findings: '', status: 0, description: 'Identifier interfaces et dépendances externes.' },
    { standard: '4.3.5', checklistValue: 0, findings: '', status: 0, description: 'Documenter le domaine d\'application.' },
    { standard: '4.4.1', checklistValue: 0, findings: '', status: 0, description: 'Établir, mettre en œuvre, tenir à jour et améliorer le SMSI.' },
    { standard: '4.4.2', checklistValue: 0, findings: '', status: 0, description: 'Définir les processus nécessaires et leurs interactions.' },
    { standard: '5.1.1', checklistValue: 0, findings: '', status: 0, description: 'Assurer l’existence d’une politique et d’objectifs compatibles avec la stratégie.' },
    { standard: '5.1.2', checklistValue: 0, findings: '', status: 0, description: 'Intégrer les exigences du SMSI dans les processus métiers.' },
    { standard: '5.1.3', checklistValue: 0, findings: '', status: 0, description: 'Assurer la disponibilité des ressources nécessaires.' },
    { standard: '5.1.4', checklistValue: 0, findings: '', status: 0, description: 'Communiquer l’importance de la sécurité de l’information.' },
    { standard: '5.1.5', checklistValue: 0, findings: '', status: 0, description: 'S’assurer de l’atteinte des résultats du SMSI.' },
    { standard: '5.1.6', checklistValue: 0, findings: '', status: 0, description: 'Soutenir les personnes dans l’efficacité du SMSI.' },
    { standard: '5.1.7', checklistValue: 0, findings: '', status: 0, description: 'Promouvoir l\'amélioration continue.' },
    { standard: '5.1.8', checklistValue: 0, findings: '', status: 0, description: 'Aider les managers à exercer leur leadership sécurité.' },
    { standard: '5.2.1', checklistValue: 0, findings: '', status: 0, description: 'Établir une politique de sécurité appropriée.' },
    { standard: '5.2.2', checklistValue: 0, findings: '', status: 0, description: 'Fournir un cadre pour les objectifs de sécurité.' },
    { standard: '5.2.3', checklistValue: 0, findings: '', status: 0, description: 'S\'engager à satisfaire aux exigences applicables.' },
    { standard: '5.2.4', checklistValue: 0, findings: '', status: 0, description: 'S\'engager à l\'amélioration continue du SMSI.' },
    { standard: '5.2.5', checklistValue: 0, findings: '', status: 0, description: 'Documenter la politique.' },
    { standard: '5.2.6', checklistValue: 0, findings: '', status: 0, description: 'Communiquer la politique en interne.' },
    { standard: '5.2.7', checklistValue: 0, findings: '', status: 0, description: 'Rendre la politique disponible aux parties intéressées.' },
    { standard: '5.3.1', checklistValue: 0, findings: '', status: 0, description: 'Attribuer et communiquer les rôles et responsabilités.' },
    { standard: '5.3.2', checklistValue: 0, findings: '', status: 0, description: 'Attribuer la responsabilité de conformité au SMSI.' },
    { standard: '5.3.3', checklistValue: 0, findings: '', status: 0, description: 'Attribuer la responsabilité du reporting des performances.' },
    { standard: '6.1.1.1', checklistValue: 0, findings: '', status: 0, description: 'Déterminer risques et opportunités liés aux enjeux 4.1 et 4.2.' },
    { standard: '6.1.1.2', checklistValue: 0, findings: '', status: 0, description: 'Assurer atteinte des résultats du SMSI.' },
    { standard: '6.1.1.3', checklistValue: 0, findings: '', status: 0, description: 'Prévenir ou réduire les effets indésirables.' },
    { standard: '6.1.1.4', checklistValue: 0, findings: '', status: 0, description: 'Renforcer l\'amélioration continue.' },
    { standard: '6.1.1.5', checklistValue: 0, findings: '', status: 0, description: 'Planifier les actions pour traiter risques/opportunités.' },
    { standard: '6.1.1.6', checklistValue: 0, findings: '', status: 0, description: 'Intégrer les actions dans les processus du SMSI.' },
    { standard: '6.1.1.7', checklistValue: 0, findings: '', status: 0, description: 'Évaluer l’efficacité de ces actions.' },
    { standard: '6.1.2.1', checklistValue: 0, findings: '', status: 0, description: 'Définir critères d’acceptation des risques.' },
    { standard: '6.1.2.2', checklistValue: 0, findings: '', status: 0, description: 'Définir critères d’appréciation des risques.' },
    { standard: '6.1.2.3', checklistValue: 0, findings: '', status: 0, description: 'Assurer cohérence et validité des appréciations.' },
    { standard: '6.1.2.4', checklistValue: 0, findings: '', status: 0, description: 'Identifier les risques de CIA sur le périmètre.' },
    { standard: '6.1.2.5', checklistValue: 0, findings: '', status: 0, description: 'Identifier les propriétaires des risques.' },
    { standard: '6.1.2.6', checklistValue: 0, findings: '', status: 0, description: 'Analyser les conséquences des risques.' },
    { standard: '6.1.2.7', checklistValue: 0, findings: '', status: 0, description: 'Évaluer la vraisemblance d’apparition.' },
    { standard: '6.1.2.8', checklistValue: 0, findings: '', status: 0, description: 'Déterminer les niveaux de risques.' },
    { standard: '6.1.2.9', checklistValue: 0, findings: '', status: 0, description: 'Comparer avec critères de risques.' },
    { standard: '6.1.2.10', checklistValue: 0, findings: '', status: 0, description: 'Prioriser les risques pour traitement.' },
    { standard: '6.1.2.11', checklistValue: 0, findings: '', status: 0, description: 'Conserver les informations documentées.' },
    { standard: '6.1.3.1', checklistValue: 0, findings: '', status: 0, description: 'Choisir options de traitement adaptées.' },
    { standard: '6.1.3.2', checklistValue: 0, findings: '', status: 0, description: 'Déterminer mesures de sécurité nécessaires.' },
    { standard: '6.1.3.3', checklistValue: 0, findings: '', status: 0, description: 'Comparer mesures avec Annexe A.' },
    { standard: '6.1.3.4', checklistValue: 0, findings: '', status: 0, description: 'Établir la Déclaration d’Applicabilité (SoA).' },
    { standard: '6.1.3.5', checklistValue: 0, findings: '', status: 0, description: 'Élaborer un plan de traitement des risques.' },
    { standard: '6.1.3.6', checklistValue: 0, findings: '', status: 0, description: 'Obtenir approbation du plan par les propriétaires.' },
    { standard: '6.1.3.7', checklistValue: 0, findings: '', status: 0, description: 'Conserver les informations documentées.' },
    { standard: '6.2.1', checklistValue: 0, findings: '', status: 0, description: 'Définir des objectifs conformes à la politique.' },
    { standard: '6.2.2', checklistValue: 0, findings: '', status: 0, description: 'Rendre les objectifs mesurables (si possible).' },
    { standard: '6.2.3', checklistValue: 0, findings: '', status: 0, description: 'Tenir compte des exigences et des résultats des risques.' },
    { standard: '6.2.4', checklistValue: 0, findings: '', status: 0, description: 'Surveiller les objectifs.' },
    { standard: '6.2.5', checklistValue: 0, findings: '', status: 0, description: 'Communiquer les objectifs.' },
    { standard: '6.2.6', checklistValue: 0, findings: '', status: 0, description: 'Mettre à jour les objectifs si nécessaire.' },
    { standard: '6.2.7', checklistValue: 0, findings: '', status: 0, description: 'Documenter les objectifs.' },
    { standard: '6.2.8', checklistValue: 0, findings: '', status: 0, description: 'Définir actions, ressources, responsables, échéances, évaluation.' },
    { standard: '6.3.1', checklistValue: 0, findings: '', status: 0, description: 'Planifier les modifications du SMSI.' },
    { standard: '7.1.1', checklistValue: 0, findings: '', status: 0, description: 'Identifier et fournir les ressources nécessaires.' },
    { standard: '7.2.1', checklistValue: 0, findings: '', status: 0, description: 'Déterminer les compétences requises.' },
    { standard: '7.2.2', checklistValue: 0, findings: '', status: 0, description: 'S\'assurer de la compétence via formation/expérience.' },
    { standard: '7.2.3', checklistValue: 0, findings: '', status: 0, description: 'Prendre actions pour combler les écarts de compétence.' },
    { standard: '7.2.4', checklistValue: 0, findings: '', status: 0, description: 'Conserver preuves des compétences.' },
    { standard: '7.3.1', checklistValue: 0, findings: '', status: 0, description: 'Sensibiliser à la politique de sécurité.' },
    { standard: '7.3.2', checklistValue: 0, findings: '', status: 0, description: 'Sensibiliser à sa contribution au SMSI.' },
    { standard: '7.3.3', checklistValue: 0, findings: '', status: 0, description: 'Sensibiliser aux implications des non-conformités.' },
    { standard: '7.4.1', checklistValue: 0, findings: '', status: 0, description: 'Définir sujets, moments, destinataires et moyens de communication.' },
    { standard: '7.5.1.1', checklistValue: 0, findings: '', status: 0, description: 'Inclure les informations documentées requises.' },
    { standard: '7.5.1.2', checklistValue: 0, findings: '', status: 0, description: 'Ajouter celles nécessaires à l’efficacité du SMSI.' },
    { standard: '7.5.2.1', checklistValue: 0, findings: '', status: 0, description: 'Définir identification et description des documents.' },
    { standard: '7.5.2.2', checklistValue: 0, findings: '', status: 0, description: 'Définir formats et supports.' },
    { standard: '7.5.2.3', checklistValue: 0, findings: '', status: 0, description: 'Revoir et approuver les documents.' },
    { standard: '7.5.3.1', checklistValue: 0, findings: '', status: 0, description: 'Assurer disponibilité et utilisation appropriée.' },
    { standard: '7.5.3.2', checklistValue: 0, findings: '', status: 0, description: 'Assurer protection contre perte/confidentialité/intégrité.' },
    { standard: '7.5.3.3', checklistValue: 0, findings: '', status: 0, description: 'Gérer distribution et accès.' },
    { standard: '7.5.3.4', checklistValue: 0, findings: '', status: 0, description: 'Gérer stockage et conservation.' },
    { standard: '7.5.3.5', checklistValue: 0, findings: '', status: 0, description: 'Gérer les modifications.' },
    { standard: '7.5.3.6', checklistValue: 0, findings: '', status: 0, description: 'Définir durée de conservation et suppression.' },
    { standard: '7.5.3.7', checklistValue: 0, findings: '', status: 0, description: 'Contrôler documents externes.' },
    { standard: '8.1.1', checklistValue: 0, findings: '', status: 0, description: 'Planifier et contrôler les processus opérationnels.' },
    { standard: '8.1.2', checklistValue: 0, findings: '', status: 0, description: 'Établir critères pour les processus.' },
    { standard: '8.1.3', checklistValue: 0, findings: '', status: 0, description: 'Documenter l\'exécution des processus.' },
    { standard: '8.1.4', checklistValue: 0, findings: '', status: 0, description: 'Contrôler les modifications prévues et imprévues.' },
    { standard: '8.1.5', checklistValue: 0, findings: '', status: 0, description: 'Contrôler produits/services externes.' },
    { standard: '8.2.1', checklistValue: 0, findings: '', status: 0, description: 'Réaliser les appréciations des risques périodiquement.' },
    { standard: '8.2.2', checklistValue: 0, findings: '', status: 0, description: 'Documenter les résultats.' },
    { standard: '8.3.1', checklistValue: 0, findings: '', status: 0, description: 'Mettre en œuvre le plan de traitement.' },
    { standard: '8.3.2', checklistValue: 0, findings: '', status: 0, description: 'Documenter les résultats du traitement.' },
    { standard: '9.1.1', checklistValue: 0, findings: '', status: 0, description: 'Déterminer ce qui doit être surveillé/mesuré.' },
    { standard: '9.1.2', checklistValue: 0, findings: '', status: 0, description: 'Définir méthodes valides et comparables.' },
    { standard: '9.1.3', checklistValue: 0, findings: '', status: 0, description: 'Définir fréquence de surveillance/mesure.' },
    { standard: '9.1.4', checklistValue: 0, findings: '', status: 0, description: 'Définir les responsables des mesures.' },
    { standard: '9.1.5', checklistValue: 0, findings: '', status: 0, description: 'Définir analyse et évaluation des résultats.' },
    { standard: '9.1.6', checklistValue: 0, findings: '', status: 0, description: 'Documenter les résultats.' },
    { standard: '9.1.7', checklistValue: 0, findings: '', status: 0, description: 'Évaluer performances et efficacité du SMSI.' },
    { standard: '9.2.1.1', checklistValue: 0, findings: '', status: 0, description: 'Réaliser audits internes planifiés.' },
    { standard: '9.2.1.2', checklistValue: 0, findings: '', status: 0, description: 'Vérifier conformité aux exigences internes et ISO.' },
    { standard: '9.2.1.3', checklistValue: 0, findings: '', status: 0, description: 'Vérifier mise en œuvre et maintien du SMSI.' },
    { standard: '9.2.2.1', checklistValue: 0, findings: '', status: 0, description: 'Planifier et maintenir un programme d’audit.' },
    { standard: '9.2.2.2', checklistValue: 0, findings: '', status: 0, description: 'Définir critères et périmètre d’audit.' },
    { standard: '9.2.2.3', checklistValue: 0, findings: '', status: 0, description: 'Sélectionner auditeurs impartiaux.' },
    { standard: '9.2.2.4', checklistValue: 0, findings: '', status: 0, description: 'Communiquer les résultats.' },
    { standard: '9.2.2.5', checklistValue: 0, findings: '', status: 0, description: 'Documenter programmes et résultats.' },
    { standard: '9.3.1.1', checklistValue: 0, findings: '', status: 0, description: 'Réaliser revue de direction périodiquement.' },
    { standard: '9.3.2.1', checklistValue: 0, findings: '', status: 0, description: 'Examiner actions précédentes.' },
    { standard: '9.3.2.2', checklistValue: 0, findings: '', status: 0, description: 'Examiner modifications enjeux internes/externes.' },
    { standard: '9.3.2.3', checklistValue: 0, findings: '', status: 0, description: 'Examiner modifications besoins des parties.' },
    { standard: '9.3.2.4', checklistValue: 0, findings: '', status: 0, description: 'Examiner performances (NC, surveillance, audit, objectifs).' },
    { standard: '9.3.2.5', checklistValue: 0, findings: '', status: 0, description: 'Examiner retours des parties intéressées.' },
    { standard: '9.3.2.6', checklistValue: 0, findings: '', status: 0, description: 'Examiner résultats des risques et plans associés.' },
    { standard: '9.3.2.7', checklistValue: 0, findings: '', status: 0, description: 'Examiner opportunités d’amélioration.' },
    { standard: '9.3.3.1', checklistValue: 0, findings: '', status: 0, description: 'Décider opportunités d’amélioration et changements.' },
    { standard: '9.3.3.2', checklistValue: 0, findings: '', status: 0, description: 'Documenter les résultats des revues.' },
    { standard: '10.1.1', checklistValue: 0, findings: '', status: 0, description: 'Améliorer en continu le SMSI.' },
    { standard: '10.2.1', checklistValue: 0, findings: '', status: 0, description: 'Réagir aux non-conformités.' },
    { standard: '10.2.2', checklistValue: 0, findings: '', status: 0, description: 'Contrôler et corriger la non-conformité.' },
    { standard: '10.2.3', checklistValue: 0, findings: '', status: 0, description: 'Traiter les conséquences.' },
    { standard: '10.2.4', checklistValue: 0, findings: '', status: 0, description: 'Rechercher causes et non-conformités similaires.' },
    { standard: '10.2.5', checklistValue: 0, findings: '', status: 0, description: 'Mettre en œuvre actions nécessaires.' },
    { standard: '10.2.6', checklistValue: 0, findings: '', status: 0, description: 'Vérifier efficacité des actions correctives.' },
    { standard: '10.2.7', checklistValue: 0, findings: '', status: 0, description: 'Modifier le SMSI si nécessaire.' },
    { standard: '10.2.8', checklistValue: 0, findings: '', status: 0, description: 'Documenter NC et actions prises.' },
    { standard: '10.2.9', checklistValue: 0, findings: '', status: 0, description: 'Documenter résultats des actions correctives.' }
]